name: Deploy St

on:
  workflow_dispatch:
    inputs:
      deploymentStage:
        description: 'Select the Deployment Stage'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stg
          - uat
          - prod

permissions:
  id-token: write

jobs:
  deploy:
    runs-on: windows-latest

    environment: ${{ github.event.inputs.deploymentStage }}

    env:
      RESOURCE_GROUP_PREFIX: "rg-eu2-latam-poc-mlops"
      DEPLOYMENT_STAGE: ${{ github.event.inputs.deploymentStage }}
      RESOURCE_TEMPLATE_FILE: "./infrastructure/bicep/st.bicep"
      RESOURCE_PARAMS_FILE: "./infrastructure/parameters/st-upbi-${{ github.event.inputs.deploymentStage }}.params.json"
      AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify folder structure
        run: |
          Get-ChildItem ./infrastructure
          Get-ChildItem ./infrastructure/parameters

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: SERVICE_PRINCIPAL
          
      - name: Validate ARM/Bicep templates
        run: |
          az deployment group validate \
            --subscription ${{ env.AZURE_SUBSCRIPTION }} \
            --resource-group ${{ env.RESOURCE_GROUP_PREFIX }}-${{ env.DEPLOYMENT_STAGE }}-001 \
            --template-file ${{ env.RESOURCE_TEMPLATE_FILE }} \
            --parameters ${{ env.RESOURCE_PARAMS_FILE }} \
            --parameters DeploymentStage=${{ env.DEPLOYMENT_STAGE }}

      - name: Deploy Resource Group
        run: |
          az deployment group create \
            --subscription ${{ env.AZURE_SUBSCRIPTION }} \
            --resource-group ${{ env.RESOURCE_GROUP_PREFIX }}-${{ env.DEPLOYMENT_STAGE }}-001 \
            --template-file ${{ env.RESOURCE_TEMPLATE_FILE }} \
            --parameters ${{ env.RESOURCE_PARAMS_FILE }} \
            --parameters DeploymentStage=${{ env.DEPLOYMENT_STAGE }}
